### ISSUE TITLE
Quick search not work when using `Cmd` + `K`

### ISSUE THREAD

**Issue by hoangnqvarmeta** [gnolang/docs.gno.land#30]

**Comment by leohhhn** [comment]
Hey @hoangnqvarmeta, thank you for finding this! @alexiscolin, can you take a look at this when you can?

**Comment by DIGIX666** [comment]
Hey @alexiscolin , I tried to find out where the problem could be coming from but I haven't found it yet. I noticed that in the default keyboard commands for Meilisearch `, yt = ["ctrl+k", "s", "/"]` , only `⌘K` doesn't work. Maybe suggesting that users use `/` could be another solution ?
<img width="137" alt="SCR-20240529-mlly" src="https://github.com/gnolang/docs.gno.land/assets/90353329/71dcd18d-e91c-47af-bae9-91778c0bfa90">
<img width="132" alt="SCR-20240529-mkme-2" src="https://github.com/gnolang/docs.gno.land/assets/90353329/170bacef-0d0f-4478-8fbb-8d44d3ba74e4">
